name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create zip file
      uses: actions/zip@v2
      with:
        files: |
          .
        exclude: |
          .git
          .github
          README.md

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Deploy to Lambda
      uses: aws-actions/aws-cli@v1
      with:
        args: lambda update-function-code --function-name my-function --zip-file fileb://./lambda.zip --region us-west-2
